# Generated by Django 5.1.4 on 2026-06-17 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCanonical',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_name', models.CharField(max_length=100, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(choices=[('Languages', 'Languages'), ('Frameworks', 'Frameworks'), ('Databases', 'Databases'), ('Tools', 'Tools'), ('Concepts', 'Concepts'), ('Cloud', 'Cloud'), ('Soft Skills', 'Soft Skills')], max_length=50)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cv_skill_canonical',
                'ordering': ['category', 'canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='CVProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, default='', max_length=100)),
                ('professional_title', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('portfolio_url', models.URLField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('template_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('completion_score', models.IntegerField(default=0)),
                ('content_updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='cv_pdfs/%Y/%m/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cv_profiles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CVLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(blank=True, choices=[('native', 'Native'), ('fluent', 'Fluent'), ('professional', 'Professional'), ('basic', 'Basic')], default='', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cv_builder.cvprofile')),
            ],
            options={
                'db_table': 'cv_languages',
                'ordering': ['order', 'language_name'],
            },
        ),
        migrations.CreateModel(
            name='CVCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('issuing_organization', models.CharField(blank=True, default='', max_length=300)),
                ('issue_month', models.IntegerField(blank=True, null=True)),
                ('issue_year', models.IntegerField(blank=True, null=True)),
                ('expiry_year', models.IntegerField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='cv_builder.cvprofile')),
            ],
            options={
                'db_table': 'cv_certifications',
                'ordering': ['order', '-issue_year', '-issue_month'],
            },
        ),
        migrations.CreateModel(
            name='CVProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('project_url', models.URLField(blank=True, default='')),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('is_professional', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cv_builder.cvprofile')),
            ],
            options={
                'db_table': 'cv_projects',
                'ordering': ['order', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='CVUploadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=300)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('raw_extracted_text', models.TextField(blank=True, default='')),
                ('ai_parsed_json', models.JSONField(blank=True, null=True)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('parsing', 'Parsing'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('scanned', 'Scanned')], default='pending', max_length=20)),
                ('fields_extracted', models.IntegerField(default=0)),
                ('fields_total', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_logs', to='cv_builder.cvprofile')),
            ],
            options={
                'db_table': 'cv_upload_logs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=300)),
                ('degree_type', models.CharField(blank=True, choices=[('bs', 'BS'), ('ms', 'MS'), ('phd', 'PhD'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('other', 'Other')], default='', max_length=50)),
                ('field_of_study', models.CharField(blank=True, default='', max_length=200)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('cgpa_scale', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('thesis_title', models.TextField(blank=True, default='')),
                ('achievements', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='cv_builder.cvprofile')),
            ],
            options={
                'verbose_name_plural': 'education entries',
                'db_table': 'cv_education',
                'ordering': ['order', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='CVSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('proficiency', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='', max_length=20)),
                ('years_of_exp', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv_builder.cvprofile')),
                ('canonical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_skills', to='cv_builder.skillcanonical')),
            ],
            options={
                'db_table': 'cv_skills',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('role_title', models.CharField(max_length=200)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract'), ('freelance', 'Freelance')], default='', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('location_type', models.CharField(blank=True, choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='', max_length=20)),
                ('start_month', models.IntegerField(blank=True, null=True)),
                ('start_year', models.IntegerField()),
                ('end_month', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='cv_builder.cvprofile')),
            ],
            options={
                'db_table': 'cv_work_experiences',
                'ordering': ['order', '-start_year', '-start_month'],
            },
        ),
        migrations.CreateModel(
            name='WorkBullet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('impact_metric', models.CharField(blank=True, max_length=255, null=True)),
                ('skills_demonstrated', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='cv_builder.workexperience')),
            ],
            options={
                'db_table': 'cv_work_bullets',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
