# Generated by Django 5.1.4 on 2026-08-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cv_photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='cvprofile',
            name='template_id',
            field=models.CharField(blank=True, choices=[('minimal', 'Minimal'), ('classic', 'Classic'), ('technical', 'Technical'), ('compact', 'Compact'), ('modern', 'Modern'), ('executive', 'Executive')], max_length=50, null=True),
        ),
    ]
