# Generated by Django 5.1.4 on 2026-09-03 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0003_cvprofile_template_id_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('bullets', 'Work bullets'), ('summary', 'Professional summary'), ('skills', 'Skills'), ('project', 'Project key points'), ('title', 'Professional title')], max_length=20)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('input_digest', models.CharField(db_index=True, max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cached_tokens', models.IntegerField(default=0)),
                ('suggestions', models.JSONField(default=dict)),
                ('accepted_index', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='cv_builder.cvprofile')),
            ],
            options={
                'db_table': 'cv_ai_suggestion_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cv', '-created_at'], name='cv_ai_log_cv_recent_idx')],
            },
        ),
    ]
