# Generated by Django 5.1.4 on 2026-09-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0004_aisuggestionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvuploadlog',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cvuploadlog',
            name='parse_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
