# Generated by Django 5.1.4 on 2026-09-09 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0005_cvuploadlog_applied_at_cvuploadlog_parse_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('profile', 'HireFlow CV'), ('upload', 'Uploaded file')], default='profile', max_length=20)),
                ('jd_text', models.TextField()),
                ('job_title', models.CharField(blank=True, default='', max_length=200)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('match_score', models.IntegerField(default=0)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('reworded_keywords', models.JSONField(blank=True, default=list)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('cover_letter', models.TextField(blank=True, default='')),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cached_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='cv_builder.cvprofile')),
                ('source_upload', models.ForeignKey(blank=True, help_text='Set when source_type is upload.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_matches', to='cv_builder.cvuploadlog')),
            ],
            options={
                'db_table': 'cv_job_matches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cv', '-created_at'], name='cv_job_match_recent_idx')],
            },
        ),
    ]
