# Generated by Django 5.1.4 on 2026-09-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0006_jobmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
