# Generated by Django 5.1.4 on 2026-09-22 11:06

import apps.cv_builder.models.cv_version
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0007_jobmatch_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvuploadlog',
            name='file_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CVVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('job_title', models.CharField(blank=True, default='', max_length=200)),
                ('match_score', models.IntegerField(default=0)),
                ('source_type', models.CharField(choices=[('profile', 'HireFlow CV'), ('upload', 'Uploaded file')], default='profile', max_length=20)),
                ('content_json', models.JSONField(blank=True, null=True)),
                ('template_id', models.CharField(blank=True, default='', max_length=50)),
                ('file_blob', models.BinaryField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, default='', max_length=300)),
                ('file_mime', models.CharField(blank=True, default='', max_length=100)),
                ('applied_rewrites', models.JSONField(blank=True, default=list)),
                ('skipped_rewrites', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=apps.cv_builder.models.cv_version.default_expiry)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cv_builder.cvprofile')),
                ('job_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_versions', to='cv_builder.jobmatch')),
            ],
            options={
                'db_table': 'cv_versions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cv', '-created_at'], name='cv_version_recent_idx')],
            },
        ),
    ]
