# Generated by Django 5.1.4 on 2026-09-10 13:49

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('greenhouse', 'Greenhouse'), ('ashby', 'Ashby'), ('lever', 'Lever'), ('workable', 'Workable')], max_length=20)),
                ('slug', models.CharField(help_text='Identifier in the ATS URL.', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_fetch_status', models.CharField(blank=True, default='', max_length=200)),
                ('last_job_count', models.IntegerField(default=0)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jobs_tracked_company',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'slug'), name='uniq_company_platform_slug')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('greenhouse', 'Greenhouse'), ('ashby', 'Ashby'), ('lever', 'Lever'), ('workable', 'Workable')], db_index=True, max_length=20)),
                ('external_id', models.CharField(max_length=120)),
                ('company_name', models.CharField(db_index=True, max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('apply_url', models.URLField(max_length=600)),
                ('location_raw', models.CharField(blank=True, default='', help_text='Exactly as the source wrote it. Never overwritten.', max_length=300)),
                ('location_city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('location_country', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('remote_type', models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('', 'Not stated')], db_index=True, default='', max_length=10)),
                ('employment_type', models.CharField(blank=True, default='', max_length=40)),
                ('department', models.CharField(blank=True, default='', max_length=200)),
                ('salary_text', models.CharField(blank=True, default='', max_length=200)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, help_text='As published by the source. May be older than reality, never newer.', null=True)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.trackedcompany')),
            ],
            options={
                'db_table': 'jobs_job',
                'ordering': ['-posted_at', '-last_seen_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='job_search_vector_gin'), models.Index(fields=['-posted_at'], name='job_posted_desc_idx'), models.Index(fields=['location_country', '-posted_at'], name='job_country_posted_idx'), models.Index(fields=['remote_type', '-posted_at'], name='job_remote_posted_idx'), models.Index(fields=['source', '-posted_at'], name='job_source_posted_idx'), models.Index(fields=['last_seen_at'], name='job_last_seen_idx'), models.Index(fields=['company', '-posted_at'], name='job_company_posted_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_job_source_external_id')],
            },
        ),
    ]
